name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Moon
        uses: moonrepo/setup-toolchain@v0
        with:
          auto-install: true

      - name: Run affected CI tasks
        run: moon ci --base origin/main
